### ISSUE TITLE
Question: How would you use GRDBQuery on large data

### ISSUE THREAD

**Issue by fbertuzzi** [groue/GRDBQuery#10]
Hey,

I'm currently working on a Chat App and using GRDBQuery for data loading from GRDB.

How would you use GRDBQuery for loading chat message?
Currently I'm fetching all messages which starts to cause large loading times and memory usage as it's all getting fetched at once.

The messages are displayed in a ScrollView which embeds a LazyVStack.

How would I use GRDBQuery for fetching just the messages currently needed, but keep the immediate loading GRDBQuery offers.

Is that possible?

**Comment by groue** [comment]
Hello @fbertuzzi,

The publisher of your `Queryable` type can only fetch and publish "the messages currently needed" (whatever it means).

If the definition of "currently needed" changes over time, you can modify the query at runtime. As an inspiration, check [this demo app](https://github.com/groue/GRDB.swift/tree/v5.20.0/Documentation/DemoApps/GRDBCombineDemo): it changes the ordering of the list fetched by its `@Query`. You should be able to adapt it in order to change the definition of "currently needed" messages instead of the ordering.

**Comment by fbertuzzi** [comment]
Hey @groue,

thank you for the fast reply! I’ll definitely have a look into the demo app. With „currently needed“ I mean which messages are currently in view + some additional ones so the user won’t notice that much of a loading time. If I change my array of messages while scrolling, wouldn’t that mess up my scrollview position as the user is scrolling from the bottom up?

**Comment by groue** [comment]
> With „currently needed“ I mean which messages are currently in view + some additional ones so the user won’t notice that much of a loading time. If I change my array of messages while scrolling, wouldn’t that mess up my scrollview position as the user is scrolling from the bottom up?

Your question is about the behavior of SwiftUI lists and stacks regarding lists that vary according to pagination or other techniques. This repository is not quite the place to ask such question, I'm sorry. I do wish I had a ready-made answer, but I have not!

**Comment by groue** [comment]
I had to close the issue since it is not related to `@Query`.

But I can give an advice: maybe do not try to tackle all problems at the same time.

I'd explore the subject of varying lists first, without any database or `@Query`. How does `LazyVStack` behave when you change a plain array as the user scrolls? Is this SwiftUI view _able_ to do what you need? You'd also be able to grab a _precise_ understanding of what "currently needed" means.

Only then I'd plug `@Query` on top of it.
