### ISSUE TITLE
`mirrorAppearanceState` and initially hidden views

### ISSUE THREAD

**Issue by kabouzeid** [groue/GRDBQuery#19]
I have a `View` within a `TabView`, and I'm using `.mirrorAppearanceState` on the `View`. Initially the `View`'s tab is not selected and thus the View is not visible.

The problem is that the `View` will now keep auto updating in the background until the respective tab is selected for the first time. `onDisappear` is not called because the `View` never appeared in the first place.

**Comment by groue** [comment]
Hello @kabouzeid,

You're correct, since `mirrorAppearanceState` detects appearance with the `onAppear` and `onDisappear` SwiftUI callbacks.

You do not report a bug in GRDBQuery.

Now, if `mirrorAppearanceState` is not the tool you need, you can still use the `isAutoupdating` binding directly, and all your SwiftUI and Combine knowledge. Please search for a solution, and report your findings!

**Comment by kabouzeid** [comment]
Thanks! I'm experimenting with different ways to get around this right now. I'll report back once I find a good solution.

What threw me off initially is this comment: https://github.com/groue/GRDBQuery/blob/b2c3a01ee17aae21c2a48f02cff9d3a900ea4656/Sources/GRDBQuery/Query.swift#L367-L379

**Comment by groue** [comment]
Thank you @kabouzeid, I'll rewrite this documentation so that it better describes the reality.

**Comment by groue** [comment]
I hope f8443a234844fdfef02dbaca1601748d1c7cc24c makes the doc less ambiguous.

---

I agree that delaying the first database access until the View appears on screen is a reasonable need. Your `TabView` example is great.

It just happens that `@Query` was first introduced in order to access the database _before_ the view is rendered for the first time (see the [Why @Query?](https://github.com/groue/GRDBQuery/blob/main/README.md#why-query) paragraph) 😅 

> I'll report back once I find a good solution.

Thank you! Maybe you'll want to perform modification to the library itself: I'll happily welcome a pull request, and guide you if you meet difficulties.

**Comment by kabouzeid** [comment]
My PR implements the behaviour I'm looking for with minimal changes: Fetch once immediately, then only start auto updating once I set `isAutoupdating = true`. The obvious drawback is that this is a breaking change because now setting `isAutoupdating = true` in `onAppear` is required for getting updates.

**Comment by groue** [comment]
> The obvious drawback is that this is a breaking change because now setting `isAutoupdating = true` in `onAppear` is required for getting updates.

Yup. This is not acceptable, I'm sorry. Dealing with the initial state of the view is the most important feature of the lib. Please read again the [Why @Query?](https://github.com/groue/GRDBQuery/blob/main/README.md#why-query) paragraph.

**Comment by kabouzeid** [comment]
The initial state is still fetched immediately (before `onAppear`), nothing has changed there. The only difference is that the publisher will not auto update after that until `isAutoupdating` is explicitly set to `true`.

**Comment by kabouzeid** [comment]
Perhaps you'll like https://github.com/groue/GRDBQuery/pull/22 better.

It allows both

```swift
@Query(Request(), in: \.database) private var values: [Value] // same as before, `isAutoupdating = true` by default
```

and

```swift
@Query(Request(), in: \.database, isAutoupdating: false) private var values: [Value]

...

.mirrorAppearanceState(to: $values.isAutoupdating)
```

**Comment by groue** [comment]
🚀 v0.3.0 has shipped with [QueryObservation](https://groue.github.io/GRDBQuery/0.3/documentation/grdbquery/queryobservation), which addresses shortcomings of `mirrorAppearanceState` and `isAutoupdating`. Most demanding applications can use the low-level `\.queryObservationEnabled` environment key. Maybe future GRDBQuery versions will ship with more observation strategies, based on user feedback and their custom use of `\.queryObservationEnabled`.
