### ISSUE TITLE
Detail pane in a NavigationSplitView not updating when selecting different sidebar item

### ISSUE THREAD

**Issue by zhenyi** [groue/GRDBQuery#50]
Hi, I'm new to GRDB and GRDBQuery. I'm making an app using SwiftUI. The app has a list of items on a sidebar and details of the clicked item on the detail pane. But, I'm having a problem. When I click on a different item in the sidebar, the details don't change.

Here is the relevant code:
```swift
struct AppView: View {
    @Environment(\.appDatabase) private var appDatabase
    @Query(TeamRequest()) private var teams: [Team]
    @State private var selectedTeam: Team?

    var body: some View {
        NavigationSplitView(sidebar: {
            List(selection: $selectedTeam) {
                ForEach(teams) { team in
                    NavigationLink(value: team) {
                        Text(team.name)
                    }
                }
            }
        }) {
            if let selectedTeam = selectedTeam {
                PlayerList(team: selectedTeam)
            } else {
                Text("No team selected")
            }
        }
    }
}
```

```swift
struct PlayerList: View {
    @Environment(\.appDatabase) private var appDatabase
    @Query<PlayerRequest> private var players: [Player]
    private let team: Team

    init(team: Team) {
        self.team = team
        _players = Query(PlayerRequest(team: team))
    }

    var body: some View {
        List {
            ForEach(players) { player in
                Text(player.name)
            }
        }
        .navigationTitle(team.name)
    }
}
```

Can you help me understand what's wrong or how to fix it? Thank you for your time.

https://github.com/zhenyi/sorry-groue/assets/2262/cdfa57bb-5a51-4c99-93bd-e12f65f8082a

**Comment by groue** [comment]
Hello @zhenyi,

Yes, you probably need to modify your code as below:

```diff
-_players = Query(PlayerRequest(team: team))
+_players = Query(constant: PlayerRequest(team: team))
```

This way, `PlayerList` can not modify the team: it is "constant", and fully determined by the enclosing view, `AppView`. The word "constant" is not very well chosen, because if `PlayerList` can not change the team, `AppView` can 😅 I hope I find a better name one day.

For more information on the three `@Query` initializers (`init(Request)`, `init(constant: Request)`, and `init(Binding<Request>`), and their different behaviors, see [Adding Parameters to Queryable Types](https://swiftpackageindex.com/groue/grdbquery/0.8.0/documentation/grdbquery/queryableparameters#Initializing-Query-from-a-Constant-Request).

**Comment by zhenyi** [comment]
I'm now getting the error `Referencing initializer 'init(constant:)' on 'Query' requires the types 'AppDatabase' and '()' be equivalent` 😬

![screenshot](https://github.com/groue/GRDBQuery/assets/2262/b4bb2971-73fc-435f-b240-ed08307e949b)

**Comment by groue** [comment]
Oh, that's because you miss one extension in your app, that allows Query to be initialized without the explicit key path to `\.appDatabase`:

```swift
// Convenience Query initializers for requests
// that feed from `AppDatabase`.
extension Query where Request.DatabaseContext == AppDatabase {
    /// Creates a `Query`, given an initial `Queryable` request that
    /// uses `DatabaseQueue` as a `DatabaseContext`.
    init(_ request: Request) {
        self.init(request, in: \.appDatabase)
    }


    /// Creates a `Query`, given a SwiftUI binding to a `Queryable`
    /// request that uses `AppDatabase` as a `DatabaseContext`.
    init(_ request: Binding<Request>) {
        self.init(request, in: \.appDatabase)
    }


    /// Creates a `Query`, given a ``Queryable`` request that uses
    /// `AppDatabase` as a `DatabaseContext`.
    init(constant request: Request) {
        self.init(constant:request, in: \.appDatabase)
    }
}
```

You probably already have the first convenience initializer defined somewhere in your app, and you are just missing the other two. This technique is described in [Getting Started with @Query](https://swiftpackageindex.com/groue/grdbquery/0.8.0/documentation/grdbquery/gettingstarted). This is a little boilerplate that is needed because not all applications use the same `AppDatabase`.

An alternative is to provide the explicit key path, but since the app has already started adding a convenience initializer, maybe it's better to adding the missing ones.

```swift
_players = Query(constant: PlayerRequest(team: team), in: \.appDatabase)
```

**Comment by zhenyi** [comment]
Thank you so much for your help! Adding the extra initializers fixed the error. I was just copying code from GRDBAsyncDemo and didn't really understand it. 😓

**Comment by groue** [comment]
It's OK to copy/paste and understand later, everybody does it! It looks like I should update the demo apps. Happy GRDB/GRDBQuery, @zhenyi!
