### ISSUE TITLE
Standalone EnvironmentStateObject

### ISSUE THREAD

**Issue by jubishop** [groue/GRDBQuery#60]
The core concept of @EnvironmentStateObject seems like an independent construction that stands separate not only from @Query but really GRDB in general.  In other words it'll work for environment injection of basically anything.  Have you considered making it its own separate library?

**Comment by groue** [comment]
Hello @jubishop,

`EnvironmentStateObject` ships with GRDBQuery so that the library can fit the needs of various architectural obediences: developers can access the database directly from the views, or from testable types (MVVM and friends).

And you're right, it is an independent construction.

> Have you considered making it its own separate library?

No, not really.

If you want `EnvironmentStateObject` without GRDBQuery, I suggest that you vendor (copy) it in your app. It is not a file that is expected to change much. You can copy and paste the [licence](https://github.com/groue/GRDBQuery/blob/main/LICENCE) at the top of the file.

Besides, the SDK now ships the `@Observable` macro. It does not work with `EnvironmentStateObject`, so I personally stopped using this property wrapper.

Apple documentation suggests using `@Observable` objects with the `@State` property wrapper, with this [important notice](https://developer.apple.com/documentation/swiftui/state#Store-observable-objects):

> A `State` property always instantiates its default value when SwiftUI instantiates the view. For this reason, avoid side effects and performance-intensive work when initializing the default value.

I consider this caveat an unbearable defect of `@State`, so instead  I use [`@ObservableState` and `WithBindable`](https://gist.github.com/groue/28369e1d99319c90dea5fb8cd305cb39):

```swift
// A testable type
@MainActor @Observable final class MyModel {
    init(myService: Service) { ... }
}

struct MyView: View {
    @Environment(\.myService) var myService // e.g. database access

    var body: some View {
        WithBindable {
            // Instantiated once in the lifetime of the view, so that the
            // initializer can perform side effects (start observing the
            // database, whatever).
            MyModel(myService: myService)
        } content: { myModel in
            ContentView(myModel: myModel)
        }
    }
}

private struct ContentView: View {
    @Bindable var myModel: MyModel

    var body: some View { ... }
}
```

Those APIs work and fit my needs, but they do not ship in GRDBQuery because I'm not sure they are stabilized enough.

**Comment by groue** [comment]
Don't hesitate becoming the owner of those short code snippets. It's also a way to learn :-)
